### ISSUE TITLE
Please consider naming collision to avoid ambiguous usage

### ISSUE THREAD

**Issue by ivanceras** [rtfeldman/elm-css#163] opened 2016-09-18 07:39 UTC
elm-css has function names that is also a function name used in elm-lang standard libraries.

example:

`Html.text` conflicts with `Css.text`, also `(width, height, rgb, etc..)`

Now I have to define a new function

```elm

txt = Html.text

```
just so I can continue writing

```elm

div [] [txt "Hello"]

```
elm solve collisions by adding `'` like in.

http://package.elm-lang.org/packages/elm-lang/html/1.1.0/Html-Attributes#type'

**Comment by tolgap** [comment] 2016-09-18 10:09
What exactly is the issue here? Your inconvenience of having to type `Html.text` instead of `text`? You could try not exposing everything from the `Css` module.

Elm does not have unsolvable naming collisions. If you have ambiguous usage, just put the module name in front of the function (as you have done in the definition of `txt`).

**Comment by ivanceras** [comment] 2016-09-18 10:59
Not a big issue really, just convenience. I usually import modules using 

```elm
import Html exposing (..)
import Css exposing (..)

```
`Html.text` is mostly used than `Css.text` without having to enumerate the other functions I used and will be used later from each modules. 

Seems likeI have to enumerate the functions is use.

**Comment by eeue56** [comment] 2016-09-18 15:42
I agree that it's not perfect. By my advice is to follow PEP 8:

```
Explicit is better than implicit.
In the face of ambiguity, refuse the temptation to guess.
Namespaces are one honking great idea -- let's do more of those!
```

At NRI, we just use `Css.name`. It's not a big deal. `Css` is three letters, and it means the API for elm-css is guessable. Making it so that every person coming from CSS/SASS/LESS now has to learn new keywords is not a good idea, sorry. I'm closing this issue as a won't fix, since it is _by design_ to have as closely matching names as possible.

**Closed by eeue56** 2016-09-18 15:42 UTC
