### ISSUE TITLE
Can't create an !important rule in inline style

### ISSUE THREAD

**Issue by duncanmalashock** [rtfeldman/elm-css#264] opened 2017-05-05 04:13 UTC
```
view : Model -> Html Msg
view model =
    let
        bg =
            backgroundColor (rgb 129 20 100) |> important
    in
        div
            [ style <| asPairs [ bg ] ]
            [ text "hi!" ]
```
I expected this would produce:
```
<div style="background-color: rgb(129, 20, 100) !important;">hi!</div>
```

But it produces this in the view of my Elm app (Chrome 57.0.2987.133):
```
<div>hi!</div>
```

Changing `bg` to 
```
bg =
  backgroundColor (rgb 129 20 100)
```
produces:
```
<div style="background-color: rgb(129, 20, 100);">hi!</div>
```

The use case is that I'm trying to build a JS-based embed with inline styles that can't be overridden by styles on the page that embeds it. `!important` rules on an inline style attribute are highest-priority, so this feature would be very helpful!

**Comment by BobWhitelock** [comment] 2017-07-01 17:00
I investigated this, and the correct list of CSS keys to values does seem to be produced when `!important` is used with `asPairs` (see https://github.com/rtfeldman/elm-css/pull/284).

In an actual app though I can reproduce this: https://ellie-app.com/3D4YPznPsNBa1/1. However, the same issue occurs if elm-css is not used at all, for example: https://ellie-app.com/3D5jYcFc6f9a1/2.

It looks like this is actually an issue in `elm-lang/html`: https://github.com/elm-lang/html/issues/99.

**Comment by rtfeldman** [comment] 2017-09-03 22:52
Closing in favor of https://github.com/elm-lang/html/issues/99

**Closed by rtfeldman** 2017-09-03 22:52 UTC
