### ISSUE TITLE
pointer-events

### ISSUE THREAD

**Issue by mordrax** [rtfeldman/elm-css#247] opened 2017-03-26 12:18 UTC
I'd like "pointer-events" to be supported. I'm happy to [attempt a PR for this](https://github.com/rtfeldman/elm-css/issues/14), but since I've only started using elm-css moments ago, it would be good to be pointed to some similar style implementations so I can see how this works.

**Comment by rtfeldman** [comment] 2017-04-17 02:48
Thanks for the issue!

Unfortunately `pointer-events` is [still in the Recommendation stage](https://www.w3.org/TR/pointerevents/) and has been since 2015. Firefox and Safari do not support it at all.

I have to draw the line somewhere for what is in-scope to be covered, and this proposal is still too preliminary for me to justify including it. 😅

**Comment by Tokap** [comment] 2017-04-21 01:00
@rtfeldman 

Hi Richard, thanks for taking the time to review this issue. I definitely understand the need to draw a line on css properties not supported by the average browser. However, [Can I Use](https://caniuse.com) seems to suggest that the JS `window.pointerEvent` remains a suggestion, while the CSS `pointer-events` property is currently supported by all major browsers.

#### Javascript `window.pointerEvent` Information:
* [Can I Use](https://caniuse.com/#feat=pointer)
* [MDN](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent)
* [W3C](https://www.w3.org/TR/2015/REC-pointerevents-20150224/#examples)

#### CSS `pointer-events` Information:
* [Can I Use](https://caniuse.com/#feat=pointer-events)
* [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events?v=example)

Based on the above information:
1. The CSS property `pointer-events` is currently supported by all major browsers.
2. The JS `window.pointerEvents` is not supported by Firefox or Safari.
3. There seems to be a well known ambiguity between the JS and CSS implementation.  The [Can I Use](https://caniuse.com/#search=pointer) article alludes to the confusion caused by this ambiguity:
>"This specification integrates various inputs from mice, touchscreens, and pens ... . Not to be mistaken with the unrelated `pointer-events` CSS property."

Therefore, given the well-known confusion, I want to ensure we are all referring to the same topic.  @mordrax, @rtfeldman were you both referring to the CSS `pointer-events` property?  If not, would you please take another look at this issue?  

Thank you for all the great work and for your attention to this issue.

**Comment by mordrax** [comment] 2017-04-21 01:14
I wasn't aware that there was `window.pointerEvent`. My reference was to the css `pointer-events` property, e.g setting `pointer-events: none` so that a mouse click is not triggered on the parent div.

**Comment by rtfeldman** [comment] 2017-04-21 01:47
You're right, @Tokap - thanks so much for pointing this out!

**Comment by rtfeldman** [comment] 2017-04-21 01:48
@mordrax if you'd like to take a stab at a PR, I'd be happy to review it!

**Comment by mordrax** [comment] 2017-04-21 02:30
O_O! onnit!

So it looks like I should add a new function in `Css.elm` much like min-height (https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L4593-L4600)

Then add some tests like these (https://github.com/rtfeldman/elm-css/blob/master/tests/Properties.elm#L77-L86)

And finally add it to the exports and property docs (https://github.com/rtfeldman/elm-css/blob/355ca480274321ac607a10696a0c261c4d7857a2/src/Css.elm#L640)

Am I on the right path here and is there anything else I'm missing?

**Comment by rtfeldman** [comment] 2017-04-21 05:10
Yep!

The tricky part will be the overloaded ones, e.g. `all`. We're using a funky type system trick to make those work; happy to explain if you'd like!

Anyway, if you search for stuff like `all :` and `visible :` for each of the "keyword values" [here](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) you'll find which ones are already defined.

Sometimes you won't need to change them. For example, `all` already has the type `All`, which is compatible only with `all` and no other values.

However, `visible : Overflow {}` means that the only way to permit `pointerEvents visible` is to also permit the other `Overflow` ones, meaning `pointerEvents hidden` would also type-check since `hidden` is a valid `Overflow` value. No good!

So `visible` will have to change to be more like `all` - you'll have to introduce a new `Visible` type and redefine `visible` to be `visible : Visible {}` so you have the level of granularity you need. This will also entail making changes to the things that currently support `visible`. The compiler and tests will help out here! 

For the non-overloaded ones, you'll presumably want to return a record like this:

```elm
{ value = "painted"
, pointerEvents = Compatible
, warnings = []
}
```

Hope that helps!

**Comment by mordrax** [comment] 2017-06-10 08:49
@rtfeldman i'm not sure if I understand your intention correctly.

It seems that `all` and `fill` are two properties that takes in values and gives back `Style`
https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L1512
https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L6730

But what I want are those functions to be used as values. So it looks to me like it fits the `displayFlex` workaround:
https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L4761-L4762

ie: 
https://github.com/rtfeldman/elm-css/pull/276/commits/cb8c8978ce143daecad2aabe15453a21eab91d7c

But this is different to what you seem to be saying. I'm confused.

**Comment by mordrax** [comment] 2017-06-10 08:55
> So visible will have to change to be more like all

Specifically, this part confuses me, `all` is a property, `visible` is a value.
If you had said, visible will have to be changed to be more like [none](https://github.com/rtfeldman/elm-css/blob/master/src/Css.elm#L4264), I think that's something I can work with.

**Comment by mordrax** [comment] 2017-06-11 11:31
@rtfeldman So let me try and explain where I'm at: https://github.com/rtfeldman/elm-css/pull/276/files

I've got a [signature for pointerEvents](https://github.com/rtfeldman/elm-css/pull/276/files#diff-854293bbb03f363ae4c16745b0af2a75R7222) that tries to be inclusive of the `all` property.

In doing so, the simpler types like [painted](https://github.com/rtfeldman/elm-css/pull/276/files#diff-854293bbb03f363ae4c16745b0af2a75R7228) needs to become functions themselves which feels wrong already *but otherwise, there's no way I can see of having `pointerEvents all` and `pointerEvents painted`*

Once I get to this point, tests compile and things should work, but then I hit `none` and `auto` which are both just simple records. I had them working previously when pointerEvents just took in a simple extensible record and I was [able to add](https://github.com/rtfeldman/elm-css/pull/276/commits/7ec74dc6de74fb30db49c5cc1da5b8bba7753656) `pointerEvents : Compatible` to both none and auto, but now that the signature is a function and the way I'm passing `painted` is [via a function](https://github.com/rtfeldman/elm-css/pull/276/files#diff-854293bbb03f363ae4c16745b0af2a75R1542) then the rest of this path looks pretty bleak as I'm going to have to wrestle none, auto into functions.

I hope you understand, more than me, what I'm talking about. Elm's really the only language so far that's taken me to such heights and made me feel that my IQ just isn't high enough to understand some of it's deeper concepts...

**Comment by rtfeldman** [comment] 2018-06-10 20:38
Closing thanks to https://github.com/rtfeldman/elm-css/pull/377 !

**Closed by rtfeldman** 2018-06-10 20:38 UTC
Labels: enhancement, help wanted
